import json
import os
import shutil
from pathlib import Path
from datetime import datetime
from typing import List, Optional
import uuid


class SampleService:
    """Service for managing MIDI samples"""

    def __init__(self):
        # Use macOS Documents folder
        self.documents_dir = Path.home() / "Documents" / "MidiCopilot" / "Samples"
        self.documents_dir.mkdir(parents=True, exist_ok=True)
        
        # Configuration file for sample metadata
        self.config_file = Path("data/config/samples.json")
        self.config_file.parent.mkdir(parents=True, exist_ok=True)
        
        self._load_samples()

    def _load_samples(self):
        """Load samples configuration from file"""
        if self.config_file.exists():
            with open(self.config_file, 'r') as f:
                self.samples = json.load(f)
        else:
            self.samples = []
            self._save_samples()

    def _save_samples(self):
        """Save samples configuration to file"""
        with open(self.config_file, 'w') as f:
            json.dump(self.samples, f, indent=2)

    def list_samples(self) -> List[dict]:
        """List all registered samples"""
        # Update file sizes and verify files exist
        valid_samples = []
        for sample in self.samples:
            path = Path(sample['path'])
            if path.exists():
                sample['size'] = path.stat().st_size
                valid_samples.append(sample)
        
        # Update samples list if any were removed
        if len(valid_samples) != len(self.samples):
            self.samples = valid_samples
            self._save_samples()
        
        return self.samples

    def add_sample(self, file_path: str, name: Optional[str] = None, 
                   source: str = "upload", metadata: Optional[dict] = None) -> dict:
        """
        Add a new sample to the collection
        
        Args:
            file_path: Path to the MIDI file
            name: Optional custom name for the sample
            source: Source of the sample (upload, generated, etc.)
            metadata: Additional metadata
            
        Returns:
            Sample info dict
        """
        source_path = Path(file_path)
        
        if not source_path.exists():
            raise ValueError(f"File not found: {file_path}")
        
        if not source_path.suffix.lower() in ['.mid', '.midi']:
            raise ValueError("File must be a MIDI file (.mid or .midi)")
        
        # Generate unique ID
        sample_id = str(uuid.uuid4())
        timestamp = datetime.now().isoformat()
        
        # Determine filename
        if name:
            filename = f"{sample_id}_{name}{source_path.suffix}"
        else:
            filename = f"{sample_id}_{source_path.name}"
        
        # Copy to Documents folder
        dest_path = self.documents_dir / filename
        shutil.copy2(source_path, dest_path)
        
        # Create sample record
        sample = {
            "id": sample_id,
            "name": name or source_path.stem,
            "filename": filename,
            "path": str(dest_path),
            "size": dest_path.stat().st_size,
            "source": source,
            "createdAt": timestamp,
            "format": source_path.suffix[1:].upper(),
            "metadata": metadata or {}
        }
        
        # Add to samples list
        self.samples.append(sample)
        self._save_samples()
        
        return sample

    def add_generated_sample(self, file_path: str, prompt_name: str, 
                           generation_params: dict) -> dict:
        """
        Add a sample generated by ARIA
        
        Args:
            file_path: Path to the generated MIDI file
            prompt_name: Name of the prompt file used
            generation_params: Generation parameters used
            
        Returns:
            Sample info dict
        """
        metadata = {
            "prompt": prompt_name,
            "parameters": generation_params,
            "generator": "ARIA"
        }
        
        name = f"ARIA_{prompt_name}_continuation"
        
        return self.add_sample(
            file_path=file_path,
            name=name,
            source="generated",
            metadata=metadata
        )

    def delete_sample(self, sample_id: str) -> bool:
        """
        Delete a sample by ID
        
        Args:
            sample_id: ID of the sample to delete
            
        Returns:
            True if deleted, False if not found
        """
        # Find the sample
        sample_index = None
        sample_path = None
        
        for i, sample in enumerate(self.samples):
            if sample['id'] == sample_id:
                sample_index = i
                sample_path = Path(sample['path'])
                break
        
        if sample_index is None:
            return False
        
        # Delete the file if it exists
        if sample_path and sample_path.exists():
            sample_path.unlink()
        
        # Remove from list
        self.samples.pop(sample_index)
        self._save_samples()
        
        return True

    def get_sample(self, sample_id: str) -> Optional[dict]:
        """Get a sample by ID"""
        for sample in self.samples:
            if sample['id'] == sample_id:
                return sample
        return None


# Global instance
_sample_service = None


def get_sample_service() -> SampleService:
    """Get or create the global SampleService instance"""
    global _sample_service
    if _sample_service is None:
        _sample_service = SampleService()
    return _sample_service