import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ViewMode, Sample } from '../types';
import { theme } from '../theme';
import { ViewToggle } from '../components/ViewToggle';
import { SampleCard } from '../components/SampleCard';
import { SampleRow } from '../components/SampleRow';
import { SampleDetail } from '../components/SampleDetail';
import { Plus, Upload, Loader2, RefreshCw } from 'lucide-react';

export const SamplesPage: React.FC = () => {
  const [viewMode, setViewMode] = useState<ViewMode>('card');
  const [selectedSample, setSelectedSample] = useState<Sample | null>(null);
  const [samples, setSamples] = useState<Sample[]>([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Fetch samples from backend
  const fetchSamples = async () => {
    setLoading(true);
    try {
      const response = await fetch('http://localhost:8000/api/samples');
      const data = await response.json();
      
      // Convert backend format to frontend format
      const formattedSamples: Sample[] = data.samples.map((s: any) => ({
        id: s.id,
        name: s.name,
        type: 'midi' as const,
        duration: 0, // We don't track duration in backend yet
        createdAt: s.createdAt,
        size: s.size,
        format: s.format,
        detailedDescription: generateDetailedDescription(s),
      }));
      
      setSamples(formattedSamples);
    } catch (error) {
      console.error('Error fetching samples:', error);
    } finally {
      setLoading(false);
    }
  };

  // Generate detailed description from sample metadata
  const generateDetailedDescription = (sample: any) => {
    let description = `## ${sample.name}\n\n`;
    
    if (sample.source === 'generated' && sample.metadata?.parameters) {
      const params = sample.metadata.parameters;
      description += `**Generated by ARIA**\n\n`;
      description += `### Generation Details\n`;
      description += `- **Prompt**: ${sample.metadata.prompt}\n`;
      description += `- **Temperature**: ${params.temperature}\n`;
      description += `- **Top P**: ${params.top_p}\n`;
      description += `- **Max Length**: ${params.max_length} tokens\n`;
      description += `- **Prompt Tokens**: ${params.prompt_tokens}\n`;
      description += `- **Generated Tokens**: ${params.generated_tokens}\n`;
    } else {
      description += `**Source**: ${sample.source === 'upload' ? 'Uploaded' : sample.source}\n`;
    }
    
    description += `\n**File**: ${sample.filename}\n`;
    description += `**Size**: ${(sample.size / 1024).toFixed(2)} KB\n`;
    description += `**Created**: ${new Date(sample.createdAt).toLocaleString()}`;
    
    return description;
  };

  // Load samples on mount and when samples change
  useEffect(() => {
    fetchSamples();
  }, []);

  // Auto-select first sample in column view
  useEffect(() => {
    if (viewMode === 'column' && !selectedSample && samples.length > 0) {
      setSelectedSample(samples[0]);
    }
  }, [viewMode, selectedSample, samples]);

  const handleSampleClick = (sample: Sample) => {
    setSelectedSample(sample);
  };

  const closeDetail = () => {
    if (viewMode === 'card') {
      setSelectedSample(null);
    }
  };

  const handleViewModeChange = (mode: ViewMode) => {
    setViewMode(mode);
    if (mode === 'card') {
      setSelectedSample(null);
    } else if (mode === 'column' && !selectedSample && samples.length > 0) {
      setSelectedSample(samples[0]);
    }
  };

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setUploading(true);
    try {
      const formData = new FormData();
      formData.append('file', file);

      const response = await fetch('http://localhost:8000/api/samples', {
        method: 'POST',
        body: formData,
      });

      const data = await response.json();
      
      if (data.success) {
        // Refresh samples list
        await fetchSamples();
      } else {
        alert('Failed to upload sample: ' + (data.error || data.message));
      }
    } catch (error) {
      console.error('Error uploading sample:', error);
      alert('Failed to upload sample');
    } finally {
      setUploading(false);
      // Reset input
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  };

  const handleDelete = async (sampleId: string) => {
    if (!confirm('Are you sure you want to delete this sample?')) return;

    try {
      const response = await fetch(`http://localhost:8000/api/samples/${sampleId}`, {
        method: 'DELETE',
      });

      const data = await response.json();
      
      if (data.success) {
        // Refresh samples list
        await fetchSamples();
        // Clear selection if deleted sample was selected
        if (selectedSample?.id === sampleId) {
          setSelectedSample(null);
        }
      } else {
        alert('Failed to delete sample: ' + (data.error || data.message));
      }
    } catch (error) {
      console.error('Error deleting sample:', error);
      alert('Failed to delete sample');
    }
  };

  const handleDownload = (sampleId: string) => {
    window.open(`http://localhost:8000/api/samples/${sampleId}/download`, '_blank');
  };

  if (viewMode === 'column') {
    return (
      <div style={{ display: 'flex', height: '100vh', overflow: 'hidden' }}>
        {/* Column view: Split screen */}
        <div style={{ width: '400px', display: 'flex', flexDirection: 'column' }}>
          <div
            style={{
              padding: theme.spacing.lg,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              background: theme.colors.glass.surface,
              backdropFilter: theme.blur.sm,
            }}
          >
            <h1
              style={{
                margin: 0,
                color: theme.colors.text.primary,
                fontSize: '1.5rem',
                fontWeight: '600',
              }}
            >
              Samples
            </h1>
            <div style={{ display: 'flex', gap: theme.spacing.md, alignItems: 'center' }}>
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={fetchSamples}
                disabled={loading}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: theme.spacing.sm,
                  padding: `${theme.spacing.sm} ${theme.spacing.md}`,
                  background: theme.colors.surface,
                  border: `1px solid ${theme.colors.border}`,
                  borderRadius: theme.borderRadius.md,
                  color: theme.colors.text.primary,
                  cursor: loading ? 'not-allowed' : 'pointer',
                  opacity: loading ? 0.5 : 1,
                }}
              >
                <RefreshCw size={16} style={loading ? { animation: 'spin 1s linear infinite' } : {}} />
                Refresh
              </motion.button>
              
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => fileInputRef.current?.click()}
                disabled={uploading}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: theme.spacing.sm,
                  padding: `${theme.spacing.sm} ${theme.spacing.md}`,
                  background: theme.colors.accent.primary,
                  border: 'none',
                  borderRadius: theme.borderRadius.md,
                  color: theme.colors.text.primary,
                  cursor: uploading ? 'not-allowed' : 'pointer',
                  opacity: uploading ? 0.5 : 1,
                }}
              >
                {uploading ? (
                  <>
                    <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} />
                    Uploading...
                  </>
                ) : (
                  <>
                    <Plus size={16} />
                    Add Sample
                  </>
                )}
              </motion.button>
              
              <ViewToggle viewMode={viewMode} onViewModeChange={handleViewModeChange} />
            </div>
          </div>

          <div style={{ flex: 1, overflow: 'auto' }}>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              style={{
                background: theme.colors.glass.surface,
                backdropFilter: theme.blur.md,
                overflow: 'hidden',
              }}
            >
              {loading ? (
                <div style={{ 
                  display: 'flex', 
                  alignItems: 'center', 
                  justifyContent: 'center', 
                  height: '200px',
                  color: theme.colors.text.secondary 
                }}>
                  <Loader2 size={32} style={{ animation: 'spin 1s linear infinite' }} />
                </div>
              ) : samples.length === 0 ? (
                <div style={{ 
                  textAlign: 'center', 
                  padding: theme.spacing.xl,
                  color: theme.colors.text.secondary 
                }}>
                  <p>No samples yet. Upload your first MIDI file!</p>
                </div>
              ) : (
                samples.map((sample) => (
                  <SampleRow
                    key={sample.id}
                    sample={sample}
                    onClick={() => handleSampleClick(sample)}
                    isSelected={selectedSample?.id === sample.id}
                  />
                ))
              )}
            </motion.div>
          </div>
        </div>

        {/* Detail panel takes remaining space */}
        <div style={{ flex: 1, background: theme.colors.background, overflow: 'auto', padding: theme.spacing.xl }}>
          {selectedSample && (
            <div style={{ position: 'relative' }}>
              <div style={{ 
                position: 'absolute', 
                top: 0, 
                right: 0, 
                display: 'flex', 
                gap: theme.spacing.sm,
                zIndex: 10
              }}>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => handleDownload(selectedSample.id)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: theme.spacing.sm,
                    padding: `${theme.spacing.sm} ${theme.spacing.md}`,
                    background: theme.colors.accent.primary,
                    border: 'none',
                    borderRadius: theme.borderRadius.md,
                    color: theme.colors.text.primary,
                    cursor: 'pointer',
                  }}
                >
                  Download
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => handleDelete(selectedSample.id)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: theme.spacing.sm,
                    padding: `${theme.spacing.sm} ${theme.spacing.md}`,
                    background: '#ff4444',
                    border: 'none',
                    borderRadius: theme.borderRadius.md,
                    color: theme.colors.text.primary,
                    cursor: 'pointer',
                  }}
                >
                  Delete
                </motion.button>
              </div>
              <SampleDetail sample={selectedSample} />
            </div>
          )}
        </div>
      </div>
    );
  }

  // Card view: Full screen with bottom drawer (better for piano rolls)
  return (
    <div style={{ position: 'relative', height: '100vh', width: '100%', overflow: 'hidden' }}>
      <div style={{ height: '100%', width: '100%', display: 'flex', flexDirection: 'column' }}>
        <div
          style={{
            padding: theme.spacing.lg,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            width: '100%',
          }}
        >
          <h1
            style={{
              margin: 0,
              color: theme.colors.text.primary,
              fontSize: '1.5rem',
              fontWeight: '600',
            }}
          >
            Samples
          </h1>
          <div style={{ display: 'flex', gap: theme.spacing.md, alignItems: 'center' }}>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={fetchSamples}
              disabled={loading}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: theme.spacing.sm,
                padding: `${theme.spacing.sm} ${theme.spacing.md}`,
                background: theme.colors.surface,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: theme.borderRadius.md,
                color: theme.colors.text.primary,
                cursor: loading ? 'not-allowed' : 'pointer',
                opacity: loading ? 0.5 : 1,
              }}
            >
              <RefreshCw size={16} style={loading ? { animation: 'spin 1s linear infinite' } : {}} />
              Refresh
            </motion.button>
            
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => fileInputRef.current?.click()}
              disabled={uploading}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: theme.spacing.sm,
                padding: `${theme.spacing.sm} ${theme.spacing.md}`,
                background: theme.colors.accent.primary,
                border: 'none',
                borderRadius: theme.borderRadius.md,
                color: theme.colors.text.primary,
                cursor: uploading ? 'not-allowed' : 'pointer',
                opacity: uploading ? 0.5 : 1,
              }}
            >
              {uploading ? (
                <>
                  <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} />
                  Uploading...
                </>
              ) : (
                <>
                  <Plus size={16} />
                  Add Sample
                </>
              )}
            </motion.button>
            
            <ViewToggle viewMode={viewMode} onViewModeChange={handleViewModeChange} />
          </div>
        </div>

        <div style={{ flex: 1, overflow: 'auto', padding: `${theme.spacing.lg} 0 ${theme.spacing.lg} ${theme.spacing.lg}` }}>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            style={{
              display: 'flex',
              flexDirection: 'row',
              gap: theme.spacing.lg,
              width: '100%',
              overflowX: 'auto',
              padding: '0 0 1rem 0',
            }}
          >
            {loading ? (
              <div style={{ 
                display: 'flex', 
                alignItems: 'center', 
                justifyContent: 'center', 
                width: '100%',
                height: '200px',
                color: theme.colors.text.secondary 
              }}>
                <Loader2 size={32} style={{ animation: 'spin 1s linear infinite' }} />
              </div>
            ) : samples.length === 0 ? (
              <div style={{ 
                textAlign: 'center', 
                width: '100%',
                padding: theme.spacing.xl,
                color: theme.colors.text.secondary 
              }}>
                <p>No samples yet. Upload your first MIDI file!</p>
              </div>
            ) : (
              samples.map((sample) => (
                <motion.div
                  key={sample.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.3 }}
                  style={{ minWidth: '300px', width: '300px', flexShrink: 0 }}
                >
                  <SampleCard
                    sample={sample}
                    onClick={() => handleSampleClick(sample)}
                    isSelected={selectedSample?.id === sample.id}
                  />
                </motion.div>
              ))
            )}
          </motion.div>
        </div>
      </div>

      {/* Bottom drawer for card view (better for piano rolls) */}
      <AnimatePresence>
        {selectedSample && (
          <>
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={closeDetail}
              style={{
                position: 'fixed',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                background: theme.colors.glass.backdrop,
                zIndex: 40,
              }}
            />
            
            {/* Bottom Drawer */}
            <motion.div
              initial={{ y: '100%' }}
              animate={{ y: 0 }}
              exit={{ y: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              style={{
                position: 'fixed',
                bottom: 0,
                left: 0,
                right: 0,
                height: '60vh',
                background: theme.colors.glass.surface,
                backdropFilter: theme.blur.md,
                zIndex: 50,
                overflow: 'auto',
                padding: theme.spacing.xl,
              }}
            >
              <div style={{ position: 'relative' }}>
                <div style={{ 
                  position: 'absolute', 
                  top: 0, 
                  right: 0, 
                  display: 'flex', 
                  gap: theme.spacing.sm,
                  zIndex: 10
                }}>
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={() => handleDownload(selectedSample.id)}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: theme.spacing.sm,
                      padding: `${theme.spacing.sm} ${theme.spacing.md}`,
                      background: theme.colors.accent.primary,
                      border: 'none',
                      borderRadius: theme.borderRadius.md,
                      color: theme.colors.text.primary,
                      cursor: 'pointer',
                    }}
                  >
                    Download
                  </motion.button>
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={() => handleDelete(selectedSample.id)}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: theme.spacing.sm,
                      padding: `${theme.spacing.sm} ${theme.spacing.md}`,
                      background: '#ff4444',
                      border: 'none',
                      borderRadius: theme.borderRadius.md,
                      color: theme.colors.text.primary,
                      cursor: 'pointer',
                    }}
                  >
                    Delete
                  </motion.button>
                </div>
                <SampleDetail sample={selectedSample} />
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Hidden file input */}
      <input
        ref={fileInputRef}
        type="file"
        accept=".mid,.midi"
        onChange={handleFileUpload}
        style={{ display: 'none' }}
      />

      <style>
        {`
          @keyframes spin {
            from {
              transform: rotate(0deg);
            }
            to {
              transform: rotate(360deg);
            }
          }
        `}
      </style>
    </div>
  );
};